### ISSUE TITLE
'safetag init' fails

### ISSUE THREAD

**Issue by poser** [contentascode/safetag#12]
`.../docsmith/utils/settings.js` is trying to read `.../node/.../bin/safetag-pkgpath`. which doesn't exist. (Using `nvm` on Tails.)

```
amnesia@amnesia:~/Persistent/src/safetag-toolkit$ safetag init
fs.js:1028
  return binding.readlink(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, readlink '/home/amnesia/Persistent/nvm/versions/node/v6.11.2/bin/safetag-pkgpath'
    at Error (native)
    at Object.fs.readlinkSync (fs.js:1028:18)
    at Object.<anonymous> (/home/amnesia/Persistent/nvm/versions/node/v6.11.2/lib/node_modules/docsmith/lib/docsmith/utils/settings.js:78:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by jmatsushita** [comment]
Hi @poser 

I had made a breaking change in `docsmith` but this should be fixed now.

Let me know if it works!

Jun
