### ISSUE TITLE
Metalsmith · failed to require plugin "metalsmith-markdown-taxonomy"

### ISSUE THREAD

**Issue by gabelula** [contentascode/safetag#16]
When trying to start it

```
  $ apprentice start
```

I get this error

```
>> Starting workspace: @apprentice/preview /Users/gaba/.content/packages/activist-apprentice-course-template/preview.yml
>> Please wait about 5 seconds while the website is built and you see the message "successfully built files."

  Metalsmith · failed to require plugin "metalsmith-markdown-taxonomy".

Error: Could not find plugin
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:120:69
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:983:17)
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:958:16
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:125:9
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:983:17)
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:958:16
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:125:9
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:983:17)
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:958:16
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:125:9


Error deploying@apprentice/preview

error Error: Could not find plugin
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:120:69
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:983:17)
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:958:16
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:125:9
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:983:17)
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:958:16
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:125:9
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:983:17)
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/node_modules/async/dist/async.js:958:16
    at /Users/gaba/.nvm/versions/node/v8.10.0/lib/node_modules/docsmith/lib/docsmith/utils/metalsmith.js:125:9

==================================================================

Please alert the developer by submitting an issue 
at https://github.com/contentascode/safetag/issues and copy the whole output of the command above.

Apologies for the inconvenience!
```

If I install metalsmith-markdown-taxonomy then I get an error with the next metalsmith package that is missing.

**Comment by jmatsushita** [comment]
Despite what the error message says, the issue queue for activist apprentice is here https://gitlab.com/contentascode/activist-apprentice/ sorry for the confusion.

Could you please provide the output of `apprentice --version`?  If it's less than `0.7.15` please update docsmith by running `npm install -g docsmith@beta`. Once this is done please remove your workspace (created during the installation https://gitlab.com/contentascode/activist-apprentice#usage) as well as your `~/.content` folder and rerun `apprentice init`. Make sure to spot any errors during this. If it works then please try `apprentice start` again.
